version: '3'

services:
    php:
        container_name: "php-fpm"
        build:
            context: ./resources/php
        environment:
            - APP_ENV=dev
            - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
        volumes:
            - ./project:/var/www

    nginx:
        container_name: "nginx"
        build:
            context: resources/nginx
        volumes:
            - ./project:/var/www
            - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        ports:
            - "81:81"
